ports:
 - port: 8888
   onOpen: open-browser
tasks:
  - name: open_jupyter
    init: "pip install --upgrade pip"
    before: "pip install -r requirements.txt"
    command: "flask run app --host=0.0.0.0 --port=8888"
